---
- name: Download Papertrail remote_syslog2
  get_url: url=https://github.com/papertrail/remote_syslog2/releases/download/{{ papertrail_version }}/remote_syslog_linux_amd64.tar.gz
           dest=/opt/remote_syslog_linux_amd64.tar.gz

- name: Extract Papertrail remote_syslog2
  unarchive: src=/opt/remote_syslog_linux_amd64.tar.gz
             dest=/opt/
             copy=no
             creates=/opt/remote_syslog/remote_syslog

- name: Configure Papertrail service definition
  template: src=remote_syslog.conf.j2 dest=/etc/init/remote_syslog.conf
  notify: Restart remote_syslog

- name: Write Papertrail configuration file
  template: src=log_files.yml.j2 dest=/etc/log_files.yml
  notify: Restart remote_syslog
