---
- name: Reload apparmor
  service: name=apparmor state=reloaded

- name: Restart remote_syslog
  service: name=remote_syslog state=restarted

- name: Restart Rsyslog
  service: name=rsyslog state=restarted
